### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by NikitaBliznyuk** [AnastasiaZheshko/TRiTPO#1]
It looks good. I like your idea about saving wishes to app.
Name "Gid" is perfect choice too. :)
You need to find a free server to let us use app through Internet.
Also integration in Google Play would be good.
By the way, you are doing a good app!

**Comment by danilchican** [comment]
I agree with NikitaBliznyuk. You should design API for your app on the remote server. Its allows you to connect to server and lead data exchange between users, because it's won't be locally.

And I think, registration is not a variant for this project. You can do registration by the social networks with full information about user, so user should not fill info oneself.
